server:
  port: 8081

spring:
  application:
    name: msvc-user
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:USERS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework:
        security: ERROR

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka