server:
  port: 8090

spring:
  application:
    name: msvc-mb-customer
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:customer
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
